/** @type {import("tailwindcss").Config} */
module.exports = {
  content: ["./app/**/*.{js,jsx,ts,tsx}", "./src/**/*.{js,jsx,ts,tsx}"],
  presets: [require("nativewind/preset")],
  theme: {
    extend: {
      colors: {
        canvas: "var(--wege-color-canvas)",
        surface: "var(--wege-color-surface)",
        ink: "var(--wege-color-ink)",
        muted: "var(--wege-color-muted)",
        line: "var(--wege-color-line)",
        sale: "var(--wege-color-sale)",
        overlay: "var(--wege-color-overlay)",
        "favorite-on": "var(--wege-color-favorite-on)",
        "favorite-off": "var(--wege-color-favorite-off)",
        "favorite-scrim": "var(--wege-color-favorite-scrim)",
        skeleton: "var(--wege-color-skeleton)",
        "skeleton-shine": "var(--wege-color-skeleton-shine)",
        fallback: "var(--wege-color-fallback)",
        card: "var(--wege-color-card)",
        "card-image": "var(--wege-color-card-image)",
      },
      fontSize: {
        header: "var(--wege-font-size-header)",
        subheader: "var(--wege-font-size-subheader)",
        name: "var(--wege-font-size-name)",
        price: "var(--wege-font-size-price)",
        "price-old": "var(--wege-font-size-price-old)",
        indicator: "var(--wege-font-size-indicator)",
        "color-label": "var(--wege-font-size-color-label)",
        "icon-sm": "var(--wege-size-icon-sm)",
        "icon-md": "var(--wege-size-icon-md)",
      },
      lineHeight: {
        tight: "18px",
        none: "20px",
      },
      letterSpacing: {
        name: "var(--wege-letter-spacing-name)",
      },
      spacing: {
        page: "var(--wege-spacing-page)",
        "page-lg": "var(--wege-spacing-page-lg)",
        "page-y": "var(--wege-spacing-page-y)",
        grid: "var(--wege-spacing-grid)",
        "meta-top": "var(--wege-spacing-meta-top)",
        meta: "var(--wege-spacing-meta)",
        swatch: "var(--wege-spacing-swatch)",
        favorite: "var(--wege-spacing-favorite)",
        "header-safe": "var(--wege-spacing-header-safe)",
        "viewer-x": "var(--wege-spacing-viewer-x)",
        "viewer-bottom": "var(--wege-spacing-viewer-bottom)",
        "grid-bottom": "var(--wege-spacing-grid-bottom)",
        "card-pad": "var(--wege-spacing-card-pad)",
        "card-gap": "var(--wege-spacing-card-gap)",
        "card-favorite": "var(--wege-spacing-card-favorite)",
        "viewer-top": "var(--wege-spacing-viewer-top)",
        "indicator-gap": "var(--wege-spacing-indicator-gap)",
        "price-gap": "var(--wege-spacing-price-gap)",
      },
      width: {
        swatch: "var(--wege-size-swatch)",
        "swatch-card": "var(--wege-size-swatch-card)",
        "swatch-viewer": "var(--wege-size-swatch-viewer)",
        "icon-sm": "var(--wege-size-icon-sm)",
        "icon-md": "var(--wege-size-icon-md)",
        "icon-lg": "var(--wege-size-icon-lg)",
        "btn-favorite": "var(--wege-size-btn-favorite)",
        "card-favorite": "var(--wege-size-card-favorite)",
        "btn-close": "var(--wege-size-btn-close)",
        dot: "var(--wege-size-dot)",
      },
      height: {
        header: "var(--wege-size-header)",
        swatch: "var(--wege-size-swatch)",
        "swatch-card": "var(--wege-size-swatch-card)",
        "swatch-viewer": "var(--wege-size-swatch-viewer)",
        "card-body-min-h": "var(--wege-card-body-min-h)",
        "card-name-min-h": "var(--wege-card-name-min-h)",
        "icon-sm": "var(--wege-size-icon-sm)",
        "icon-md": "var(--wege-size-icon-md)",
        "icon-lg": "var(--wege-size-icon-lg)",
        "btn-favorite": "var(--wege-size-btn-favorite)",
        "card-favorite": "var(--wege-size-card-favorite)",
        "btn-close": "var(--wege-size-btn-close)",
        dot: "var(--wege-size-dot)",
      },
      borderRadius: {
        card: "var(--wege-radius-card)",
        full: "var(--wege-radius-full)",
      },
      maxWidth: {
        gallery: "var(--wege-max-width-gallery)",
      },
      aspectRatio: {
        product: "var(--wege-aspect-product-w) / var(--wege-aspect-product-h)",
      },
      boxShadow: {
        card: "var(--wege-shadow-card)",
        viewer: "var(--wege-shadow-viewer)",
      },
      keyframes: {
        skeleton: {
          "0%, 100%": { opacity: "1" },
          "50%": { opacity: "0.45" },
        },
        shimmer: {
          "0%": { transform: "translateX(-100%)" },
          "100%": { transform: "translateX(100%)" },
        },
      },
      animation: {
        skeleton: "skeleton 1.5s ease-in-out infinite",
        shimmer: "shimmer 1.4s ease-in-out infinite",
      },
    },
  },
  plugins: [],
};
