import type { ImageSourcePropType } from "react-native";

const sources = {
  "01-linen-shirt/black-1.png": require("../../assets/products/01-linen-shirt/black-1.png"),
  "01-linen-shirt/black-2.png": require("../../assets/products/01-linen-shirt/black-2.png"),
  "01-linen-shirt/black-3.png": require("../../assets/products/01-linen-shirt/black-3.png"),
  "01-linen-shirt/ivory-1.png": require("../../assets/products/01-linen-shirt/ivory-1.png"),
  "01-linen-shirt/ivory-2.png": require("../../assets/products/01-linen-shirt/ivory-2.png"),
  "01-linen-shirt/sage-1.png": require("../../assets/products/01-linen-shirt/sage-1.png"),
  "02-wool-coat/camel-1.png": require("../../assets/products/02-wool-coat/camel-1.png"),
  "02-wool-coat/camel-2.png": require("../../assets/products/02-wool-coat/camel-2.png"),
  "02-wool-coat/charcoal-1.png": require("../../assets/products/02-wool-coat/charcoal-1.png"),
  "02-wool-coat/charcoal-2.png": require("../../assets/products/02-wool-coat/charcoal-2.png"),
  "02-wool-coat/charcoal-3.png": require("../../assets/products/02-wool-coat/charcoal-3.png"),
  "02-wool-coat/charcoal-4.png": require("../../assets/products/02-wool-coat/charcoal-4.png"),
  "03-crew-knit/burgundy-1.png": require("../../assets/products/03-crew-knit/burgundy-1.png"),
  "03-crew-knit/navy-1.png": require("../../assets/products/03-crew-knit/navy-1.png"),
  "03-crew-knit/navy-2.png": require("../../assets/products/03-crew-knit/navy-2.png"),
  "03-crew-knit/oat-1.png": require("../../assets/products/03-crew-knit/oat-1.png"),
  "03-crew-knit/oat-2.png": require("../../assets/products/03-crew-knit/oat-2.png"),
  "03-crew-knit/oat-3.png": require("../../assets/products/03-crew-knit/oat-3.png"),
  "04-trouser/black-1.png": require("../../assets/products/04-trouser/black-1.png"),
  "04-trouser/black-2.png": require("../../assets/products/04-trouser/black-2.png"),
  "04-trouser/black-3.png": require("../../assets/products/04-trouser/black-3.png"),
  "04-trouser/stone-1.png": require("../../assets/products/04-trouser/stone-1.png"),
  "04-trouser/stone-2.png": require("../../assets/products/04-trouser/stone-2.png"),
  "05-slip-dress/champagne-1.png": require("../../assets/products/05-slip-dress/champagne-1.png"),
  "05-slip-dress/champagne-2.png": require("../../assets/products/05-slip-dress/champagne-2.png"),
  "05-slip-dress/champagne-3.png": require("../../assets/products/05-slip-dress/champagne-3.png"),
  "05-slip-dress/ink-1.png": require("../../assets/products/05-slip-dress/ink-1.png"),
  "05-slip-dress/ink-2.png": require("../../assets/products/05-slip-dress/ink-2.png"),
  "06-trucker/indigo-1.png": require("../../assets/products/06-trucker/indigo-1.png"),
  "06-trucker/indigo-2.png": require("../../assets/products/06-trucker/indigo-2.png"),
  "06-trucker/wash-1.png": require("../../assets/products/06-trucker/wash-1.png"),
  "06-trucker/wash-2.png": require("../../assets/products/06-trucker/wash-2.png"),
  "06-trucker/wash-3.png": require("../../assets/products/06-trucker/wash-3.png"),
  "07-cardigan/black-1.png": require("../../assets/products/07-cardigan/black-1.png"),
  "07-cardigan/forest-1.png": require("../../assets/products/07-cardigan/forest-1.png"),
  "07-cardigan/forest-2.png": require("../../assets/products/07-cardigan/forest-2.png"),
  "07-cardigan/greige-1.png": require("../../assets/products/07-cardigan/greige-1.png"),
  "07-cardigan/greige-2.png": require("../../assets/products/07-cardigan/greige-2.png"),
  "08-midi-skirt/chocolate-1.png": require("../../assets/products/08-midi-skirt/chocolate-1.png"),
  "08-midi-skirt/chocolate-2.png": require("../../assets/products/08-midi-skirt/chocolate-2.png"),
  "08-midi-skirt/chocolate-3.png": require("../../assets/products/08-midi-skirt/chocolate-3.png"),
  "08-midi-skirt/white-1.png": require("../../assets/products/08-midi-skirt/white-1.png"),
  "08-midi-skirt/white-2.png": require("../../assets/products/08-midi-skirt/white-2.png"),
  "09-turtleneck/cream-1.png": require("../../assets/products/09-turtleneck/cream-1.png"),
  "09-turtleneck/cream-2.png": require("../../assets/products/09-turtleneck/cream-2.png"),
  "09-turtleneck/heather-1.png": require("../../assets/products/09-turtleneck/heather-1.png"),
  "09-turtleneck/heather-2.png": require("../../assets/products/09-turtleneck/heather-2.png"),
  "09-turtleneck/heather-3.png": require("../../assets/products/09-turtleneck/heather-3.png"),
  "09-turtleneck/heather-4.png": require("../../assets/products/09-turtleneck/heather-4.png"),
  "10-trench/black-1.png": require("../../assets/products/10-trench/black-1.png"),
  "10-trench/black-2.png": require("../../assets/products/10-trench/black-2.png"),
  "10-trench/khaki-1.png": require("../../assets/products/10-trench/khaki-1.png"),
  "10-trench/khaki-2.png": require("../../assets/products/10-trench/khaki-2.png"),
  "10-trench/khaki-3.png": require("../../assets/products/10-trench/khaki-3.png"),
  "11-chino/olive-1.png": require("../../assets/products/11-chino/olive-1.png"),
  "11-chino/olive-2.png": require("../../assets/products/11-chino/olive-2.png"),
  "11-chino/olive-3.png": require("../../assets/products/11-chino/olive-3.png"),
  "11-chino/sand-1.png": require("../../assets/products/11-chino/sand-1.png"),
  "11-chino/sand-2.png": require("../../assets/products/11-chino/sand-2.png"),
  "12-blazer/grey-1.png": require("../../assets/products/12-blazer/grey-1.png"),
  "12-blazer/ivory-1.png": require("../../assets/products/12-blazer/ivory-1.png"),
  "12-blazer/ivory-2.png": require("../../assets/products/12-blazer/ivory-2.png"),
  "12-blazer/navy-1.png": require("../../assets/products/12-blazer/navy-1.png"),
  "12-blazer/navy-2.png": require("../../assets/products/12-blazer/navy-2.png"),
  "12-blazer/navy-3.png": require("../../assets/products/12-blazer/navy-3.png"),
} as const satisfies Record<string, ImageSourcePropType>;

export function productImageSource(path: string): ImageSourcePropType {
  const source = sources[path as keyof typeof sources];
  if (!source) {
    throw new Error(`Missing product image: ${path}`);
  }
  return source;
}
